# v2 syntax
version: '2'

services:

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: st-visual-app
    volumes:
      - .:/var/www/app
    ports:
      - "82:8080"